# Site settings
title: "Muhammad Attia"
email: muhammad.mattia@gmail.com
description: "Android Software Engineer"
baseurl: ""
url: "https://muhammadattia.github.io"
title_description: "I'm a Software Engineer with a passion for Android Development,problem-solving, Programming Competitions, and Machine Learning."
title_image: "https://s.gravatar.com/avatar/6c05d7a860832c2a18c048d041f19e92?s=80"
google_analytics: "UA-20365477-4"
disqus_account: muhammad_attia
github_repository: https://github.com/MuhammadAttia/muhammadattia.github.io
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: MuhammadAttia95
github_username:  MuhammadAttia
#instagram_username: 
#reddit_username: 
linkedin_link: https://www.linkedin.com/in/muhammadattia95/
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
xing_link:
facebook_link: https://www.facebook.com/MuhammadAttia95

# Footer
footer_left: "Muhammad Attia 2017"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
